apiVersion: template.openshift.io/v1
kind: List
labels:
  template: strimzi-ephemeral-kafka
metadata:
  annotations:
    description: >-
      Creates a small ephemeral kafka cluster.
    openshift.io/display-name: Kafka Ephemeral List
    tags: instant-app
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: strimzi-cluster-operator
    labels:
      app: strimzi
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    name: strimzi-cluster-operator-binding
    labels:
      app: strimzi
  subjects:
    - kind: ServiceAccount
      name: strimzi-cluster-operator
  roleRef:
    kind: ClusterRole
    name: edit
    apiGroup: rbac.authorization.k8s.io
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: strimzi-cluster-operator
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: strimzi-cluster-operator
      spec:
        serviceAccountName: strimzi-cluster-operator
        containers:
          - name: strimzi-cluster-operator
            image: strimzi/cluster-operator:0.4.0
            env:
              - name: STRIMZI_CONFIGMAP_LABELS
                value: "strimzi.io/kind=cluster"
              - name: STRIMZI_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
                value: "120000"
              - name: STRIMZI_OPERATION_TIMEOUT_MS
                value: "300000"
              - name: STRIMZI_DEFAULT_ZOOKEEPER_IMAGE
                value: strimzi/zookeeper:0.4.0
              - name: STRIMZI_DEFAULT_KAFKA_IMAGE
                value: strimzi/kafka:0.4.0
              - name: STRIMZI_DEFAULT_KAFKA_CONNECT_IMAGE
                value: strimzi/kafka-connect:0.4.0
              - name: STRIMZI_DEFAULT_KAFKA_CONNECT_S2I_IMAGE
                value: strimzi/kafka-connect-s2i:0.4.0
              - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
                value: strimzi/topic-operator:0.4.0
            livenessProbe:
              httpGet:
                path: /healthy
                port: 8080
              initialDelaySeconds: 10
              periodSeconds: 30
            readinessProbe:
              httpGet:
                path: /ready
                port: 8080
              initialDelaySeconds: 10
              periodSeconds: 30
            resources:
              limits:
                memory: 192Mi
                cpu: 1000m
              requests:
                memory: 192Mi
                cpu: 100m
    strategy:
      type: Recreate
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      strimzi.io/kind: cluster
      strimzi.io/type: kafka
    name: my-cluster
  data:
    kafka-config: |-
      {
        "num.partitions": 1,
        "num.recovery.threads.per.data.dir": 1,
        "default.replication.factor": 1,
        "offsets.topic.replication.factor": 1,
        "transaction.state.log.replication.factor": 1,
        "transaction.state.log.min.isr": 1,
        "log.retention.hours": 168,
        "log.segment.bytes": 1073741824,
        "log.retention.check.interval.ms": 300000,
        "num.network.threads": 3,
        "num.io.threads": 8,
        "socket.send.buffer.bytes": 102400,
        "socket.receive.buffer.bytes": 102400,
        "socket.request.max.bytes": 104857600,
        "group.initial.rebalance.delay.ms": 0
      }
    kafka-healthcheck-delay: '15'
    kafka-healthcheck-timeout: '5'
    kafka-jvmOptions: |-
      {
        "-Xmx": "256M",
        "-Xms": "256M"
      }
    kafka-nodes: '1'
    kafka-resources: |-
      {
        "requests": {
          "cpu": "200m",
          "memory": "512Mi"
        },
        "limits": {
          "cpu": "1",
          "memory": "512Mi"
        }
      }
    kafka-storage: '{ "type": "ephemeral" }'
    topic-operator-config: |-
      { 
        "resources": {
          "requests": {
            "cpu": "100m",
            "memory": "128Mi"
          },
          "limits": {
            "cpu": "1",
            "memory": "128Mi"
          }
        }
      }
    zookeeper-healthcheck-delay: '15'
    zookeeper-healthcheck-timeout: '5'
    zookeeper-nodes: '1'
    zookeeper-resources: |-
      {
        "requests": {
          "cpu": "200m",
          "memory": "128Mi"
        },
        "limits": {
          "cpu": "1",
          "memory": "128Mi"
        }
      }
    zookeeper-storage: '{ "type": "ephemeral" }'
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: favorites
    labels:
      strimzi.io/kind: topic
      strimzi.io/cluster: my-cluster
  data:
    name: favorites
    partitions: "1"
    replicas: "1"
    config: |-
      {
        "retention.bytes": "1073741824",
        "retention.ms": "86400000",
        "segment.bytes": "1073741824"
      }