apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: vertx-app-deploy-template
metadata:
  annotations:
    description: A template to deploy your Vert.x app with an HTTP endpoint
    iconClass: icon-cube
    openshift.io/display-name: Vert.x App Deploy Template
    tags: vertx
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: '${APP_NAME}'
    name: '${APP_NAME}'
    namespace: '${NAMESPACE}'
  spec: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: '${APP_NAME}'
    name: '${APP_NAME}'
  spec:
    replicas: 1
    selector:
      name: '${APP_NAME}'
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: '${APP_NAME}'
      spec:
        containers:
          - image: '${APP_NAME}'
            imagePullPolicy: Always
            name: '${APP_NAME}'
            env:
            - name: KUBERNETES_NAMESPACE
              value: ${targetNamespace}
            - name: JAVA_OPTIONS
              value: '-Djava.net.preferIPv4Stack=true -Dvertx.jgroups.config=default-configs/default-jgroups-kubernetes.xml -Dorg.slf4j.simpleLogger.log.org.jgroups=WARN -Dorg.slf4j.simpleLogger.log.org.infinispan=WARN'
            - name: JAVA_ARGS
              value: '-cluster -cluster-port 5800'
            ports:
              - containerPort: 5800
                protocol: TCP
              - containerPort: 8778
                protocol: TCP
              - containerPort: 8080
                protocol: TCP
            livenessProbe:
                failureThreshold: 3
                tcpSocket:
                  port: 5800
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
            readinessProbe:
              failureThreshold: 3
              tcpSocket:
                port: 5800
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            resources: {}
            terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - '${project}'
          from:
            kind: ImageStreamTag
            name: '${APP_NAME}:latest'
        type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: '${APP_NAME}'
    name: '${APP_NAME}'
  spec:
    ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 8080
      - name: jolokia
        port: 8778
        protocol: TCP
        targetPort: 8778
      - name: cluster
        port: 5800
        protocol: TCP
        targetPort: 5800
    selector:
      name: '${project}'
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      name: '${APP_NAME}'
    name: '${APP_NAME}'
  spec:
    port:
      targetPort: http
    to:
      kind: Service
      name: '${APP_NAME}'
      weight: 100
    wildcardPolicy: None
parameters:
  - description: The name assigned to all objects and the related imagestream.
    displayName: Name
    name: APP_NAME
    required: true
  - description: The project/namespace where the application is deployed.
    displayName: Project/Namespace for the application
    name: NAMESPACE
    required: true
